services:
  - type: web
    name: biogram
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn biogram.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: biogram-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"

databases:
  - name: biogram-db
    plan: free
    databaseName: biogram
    user: biogram
